; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.0-rc1"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.2"

projects[eva][subdir] = "contrib"
projects[eva][version] = "1.1"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0-beta6"

projects[lightbox2][subdir] = "contrib"
projects[lightbox2][version] = "1.0-beta1"

projects[references][subdir] = "contrib"
projects[references][version] = "2.0"

projects[nodereference_url][subdir] = "contrib"
projects[nodereference_url][version] = "1.12"

projects[token][subdir] = "contrib"
projects[token][version] = "1.0-rc1"

projects[views][subdir] = "contrib"
projects[views][version] = "3.3"

; Themes
projects[a-cloudy-day][version] = "1.0"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[dug_2012_03_photo_gallery][download][type] = ""
;projects[dug_2012_03_photo_gallery][download][url] = ""
;projects[dug_2012_03_photo_gallery][type] = "module"


